<?php

/**
 * @file
 * Allow users to view all hidden nodes, or hidden nodes
 * of a specific type.
 */

/**
 * Implementation of hook_perm().
 *
 * Adds a global 'view all hidden content' permission and also
 * a new permission for each content type.
 */
function hidden_nodes_perm() {
  $perms = array('view all hidden content');

  foreach (node_get_types() as $type => $name) {
    $perms[] = 'view hidden ' . $type . ' content';
  }

  return $perms;
}

/**
 * Implementation of hook_menu().
 */
function hidden_nodes_menu() {
  $items = array();
  $items['admin/settings/hidden_nodes'] = array(
    'title' => 'Hidden nodes',
    'description' => 'Settings for Hidden nodes module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hidden_nodes_setting_page'),
    'file' => 'hidden_nodes.admin.inc',
    'access arguments' => array('administer site configuration'),
  );
	return $items;
}

/**
 * Implementation of hook_menu_alter().
 *
 * Modifies the path node/nid to use our access callback.
 */
function hidden_nodes_menu_alter(&$items) {
  $old_access_callback = $items['node/%node']['access callback'];
  $old_access_arguments = $items['node/%node']['access arguments'];
  $items['node/%node']['access callback'] = '_hidden_nodes_node_access';
  $items['node/%node']['access arguments'] = array(1, $old_access_callback, $old_access_arguments);
}

/**
 * Implementation of hook_nodeapi().
 */
function hidden_nodes_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'load':
      // attempt to set hidden value
      $result = db_query("SELECT hidden FROM {hidden_nodes} WHERE nid=%d", $node->nid);
      $val = db_fetch_array($result);
			// if this module was turned on after the fact, nodes won't have a value
      if (isset($val['hidden'])) {
        $node->hidden = $val['hidden'];
      }
      else {
        $node->hidden = 0;
      }
    break;
		case 'delete':
		  // clean up on node delete
		  db_query("DELETE FROM {hidden_nodes} WHERE nid=%d", $node->nid);
		break;
  }
}

/**
 * Returns true if the user has 'view all hidden content' or if
 * they have the permission corresponding to the node's content type.
 */
function _hidden_nodes_node_access($node, $old_access_callback, $old_access_arguments) {
  // Only check permissions on nodes that are hidden.
  if ($node->hidden == 0) {
    if (user_access('view all hidden content')) {
      return TRUE;
    }

    if (user_access('view hidden ' . $node->type . ' content')) {
      return TRUE;
    }
  }
  // If none of the above conditions were satisfied, then use the original callback.
  $old_access_arguments[1] = $node; // arg 1 is node object
  return call_user_func_array($old_access_callback, $old_access_arguments);
}

/**
 * Implements hook_form_alter().
 */
function hidden_nodes_form_alter(&$form, $form_state, $form_id) {
  // inject new option to hide node onto all node forms
  if (isset($form['type']['#value']) && $form['type']['#value'] . '_node_form' == $form_id) {
    // Get a copy of the current node object.
    $node = $form['#node'];
    // add field to the form if the setting is there for it
    if (variable_get('hidden_node_type_'. $node->type, 0)) {
      $form['hidden_node'] = array(
        '#type' => 'checkbox',
        '#title' => t('Hide node'),
        '#default_value' => $node->hidden,
        '#description' => t('Hide this node from those without the permission to view hidden nodes.'),
        '#access' => user_access('administer nodes') || user_access('view all hidden content') || user_access('view hidden ' . $node->type . ' content'),
      );
			$form['#submit'][] = '_hidden_nodes_submit_handler';
    }
  }
}

/**
 * Submit handler for processing the hidden node checkbox.
 */
function _hidden_nodes_submit_handler($form, &$form_state) {
  if (isset($form_state['values']['hidden_node'])) {
		$form['#node']->hidden = check_plain($form_state['values']['hidden_node']);
	}
}
// @todo: add submit handler for the checkbox value above
// also add the checkbox into a fieldset just to make things cleaner
// use elms packaging funness to bundle default settings
// override language to be content centric